/*
 * Interface wording in English and Bengali. Content (names, events, looks,
 * polls) lives in js/config.js; this file is the page's own words.
 *
 * {placeholders} are filled by Invite.t(key, vars). Keep the same keys in
 * both languages; a missing Bengali key falls back to English.
 *
 * The Bengali was drafted by Claude and MUST be read by a Bengali-speaking
 * family member before guests see it. Mark `_reviewedBy` when done.
 */
window.INVITE_STRINGS = {
  en: {
    _reviewedBy: "",
    "meta.title": "{groom} & {bride} — you're invited",
    "lang.label": "Language",
    "lang.switchTo": "বাংলায় পড়ুন",

    "curtain.greeting": "An invitation for you",
    "curtain.greetingNamed": "An invitation for {name}",
    "curtain.open": "Open invitation",

    "notFound.metaTitle": "Invitation not found · {groom} & {bride}",
    "notFound.kicker": "Invitation not found",
    "notFound.title": "This invitation wandered off to another wedding",
    "notFound.body": "We looked under the mandap, behind the shehnai and even in Mashi's handbag, but no invitation matches this link.",
    "notFound.hint": "Please open the link exactly as it was sent to you on WhatsApp, or ask the family for a new one.",
    "notFound.ask": "Ask the family on WhatsApp",
    "notFound.call": "Call {name}",
    "sound.withSound": "With sound",
    "sound.withoutSound": "Without sound",
    "sound.mute": "Turn music off",
    "sound.unmute": "Turn music on",
    "ambient.shankh": "Blow the shankh",
    "ambient.openStory": "Open its wedding story",

    "nav.top": "Back to top",
    "nav.sections": "Sections",
    "nav.gallery": "Gallery",
    "nav.events": "Events",
    "nav.rituals": "Ritual guide",
    "nav.polls": "Polls",
    "nav.rsvp": "RSVP",

    "hero.dear": "Dear {name},",
    // Kept in Bengali on the English page, at the family's request.
    "hero.blessingTitle": "শুভ পরিণয়: অনুরাগের রঙে আঁকা এক নতুন দিগন্ত",
    "hero.reply": "Reply to the invitation",
    "hero.seeEvents": "See the events",
    "hero.stageLabel": "An illustration of {groom} and {bride}",
    "looks.label": "Change their outfit",

    "countdown.untilStart": "Wedding Countdown",
    "countdown.untilEvent": "Wedding Countdown",
    "countdown.begun": "The celebrations have begun",
    "countdown.over": "Thank you for celebrating with us",
    "countdown.days": "days",
    "countdown.hours": "hours",
    "countdown.minutes": "minutes",
    "countdown.seconds": "seconds",

    "families.title": "Our families",
    "families.intro": "Two families, coming together with joy.",
    "families.bride": "The bride",
    "families.groom": "The groom",
    "families.joiner": "&",

    "rituals.title": "What happens at a Bengali wedding?",
    "rituals.intro": "A little guide for guests joining us for the first time.",
    "rituals.pending": "Awaiting confirmation",
    "rituals.confirmed": "Included in our celebration",
    "rituals.pendingNotice": "The family is confirming which of these rituals will take place.",
    "rituals.confirmedNotice": "{n} ritual(s) are confirmed; the rest may vary with family tradition.",
    "rituals.objectStory": "A wedding object",

    "dayMode.label": "Wedding-day information",
    "dayMode.kicker": "Wedding-day mode",
    "dayMode.happening": "Happening now: {event}",
    "dayMode.next": "Next: {event} at {time}",
    "dayMode.lagna": "the lagna time",
    "dayMode.timeSoon": "a time to be confirmed",
    "dayMode.celebration": "the celebration",
    "dayMode.map": "Open map & schedule",
    "dayMode.contacts": "Family contacts",
    "dayMode.call": "Call",
    "dayMode.offline": "This page and the essential day details are available offline after your first visit.",

    "gallery.title": "The two of us",
    "gallery.intro": "A few of our favourite moments together.",
    "gallery.openLarger": "{label}. Open larger",
    "gallery.emptyTitle": "Real photos are on their way",
    "gallery.emptyBody": "We're choosing our favourites. Look again closer to December.",
    "gallery.storyCount": "{current} of {total}",
    "gallery.like": "Like this photo",
    "gallery.previous": "Previous photo",
    "gallery.next": "Next photo",
    "gallery.defaultComment": "A little moment, saved for later.",

    "events.title": "Four days in Kolkata",
    "events.intro": "Times and venues appear here as soon as they're fixed.",
    "events.time": "Time",
    "events.venue": "Venue",
    "events.tba": "To be announced",
    "events.from": "From {time}",
    "events.done": "Done",
    "events.today": "Today",
    "events.tomorrow": "Tomorrow",
    "events.inDays": "In {n} days",
    "events.directions": "Directions",
    "events.addToCalendar": "Add to calendar",
    "events.addAria": "Add the {event} to your calendar",
    "events.venueSoon": "We'll share the venue here as soon as it's confirmed.",
    "events.getDirections": "Get directions",
    "events.mapOf": "Map of {place}",
    // For an invite to some of the events (js/invites.js), by the number of days it covers.
    "events.titleDays1": "Join us in Kolkata",
    "events.titleDays2": "Two days in Kolkata",
    "events.titleDays3": "Three days in Kolkata",
    "dialog.close": "Close",

    "contact.open": "Contact the family",
    "contact.title": "Call or WhatsApp us",
    "contact.groom": "Groom's side",
    "contact.bride": "Bride's side",
    "contact.call": "Call {name} on {number}",
    "contact.whatsapp": "WhatsApp {name} on {number}",

    "polls.or": "or",
    "polls.intro": "Pick a side on each one, or skip it.",
    "polls.count": "{i} of {n}",
    "polls.skip": "Skip this one",
    "polls.next": "Next question",
    "polls.seeResults": "See your picks",
    "polls.votes": "{n} votes",
    "polls.oneVote": "1 vote",
    "polls.early": "Early days: {n} so far",
    "polls.yourPicks": "Your picks",
    "polls.allGroom": "You're firmly #TeamGroom.",
    "polls.allBride": "You're firmly #TeamBride.",
    "polls.balanced": "Perfectly balanced. Both families approve.",
    "polls.skippedAll": "You skipped them all. Very diplomatic.",
    "polls.everyone": "All guests so far",
    "polls.again": "Answer again",

    "rsvp.title": "Will you join us?",
    "rsvp.intro": "Let us know either way.",
    "rsvp.deadline": "Please reply by {date}. Let us know either way.",
    "rsvp.name": "Your name",
    "rsvp.phone": "WhatsApp number",
    "rsvp.phonePlaceholder": "+91 98xxx xxxxx",
    "rsvp.reply": "Your reply",
    "rsvp.yes": "Joyfully accept",
    "rsvp.no": "Regretfully decline",
    "rsvp.events": "Which events will you come to?",
    "rsvp.guests": "Guests, including you",
    "rsvp.fewer": "One fewer guest",
    "rsvp.more": "One more guest",
    "rsvp.food": "Food preference",
    "rsvp.dietNotes": "Allergies or other needs",
    "rsvp.dietNotesPlaceholder": "e.g. no peanuts, one child's meal",
    "rsvp.wishes": "Wishes for the couple",
    "rsvp.optional": "optional",
    "rsvp.send": "Send my reply",
    "rsvp.sending": "Sending…",
    "rsvp.errName": "Enter your name so we know who's replying.",
    "rsvp.errPhone": "Enter a phone number we can reach you on, with country code if outside India.",
    "rsvp.errAttending": "Choose whether you can come.",
    "rsvp.errEvents": "Choose at least one event.",
    "rsvp.errOffline": "You seem to be offline, so your reply hasn't been sent yet. Your answers are still here: connect to the internet and press Send my reply again.",
    "rsvp.errSlow": "Sending is taking longer than usual, so we couldn't confirm your reply. Please wait a moment and press Send my reply again.",
    "rsvp.errServer": "Sorry, something went wrong on our side and your reply wasn't saved. Your answers are still here: please try again in a few minutes. If it keeps happening, let us know on WhatsApp.",
    "rsvp.thanksYes": "Thank you, {name}!",
    "rsvp.thanksNo": "Thank you for letting us know, {name}.",
    "rsvp.savedOne": "We've saved a place for you (replied on {date}). We can't wait to celebrate with you.",
    "rsvp.savedMany": "We've saved {n} places (replied on {date}). We can't wait to celebrate with you.",
    "rsvp.missed": "You'll be missed, and you'll be in our thoughts on the day (replied on {date}).",
    "rsvp.change": "Change my reply",

    "footer.blessing": "With love and blessings from both our families.",
    "footer.petalsOff": "Pause falling petals",
    "footer.petalsOn": "Play falling petals",
    "footer.sound": "Sound",
  },

  bn: {
    _reviewedBy: "",
    "meta.title": "{groom} ও {bride} — আপনাকে সাদর আমন্ত্রণ",
    "lang.label": "ভাষা",
    "lang.switchTo": "Read in English",

    "curtain.greeting": "আপনার জন্য একটি আমন্ত্রণ",
    "curtain.greetingNamed": "প্রিয় {name}, আপনাকে সাদর আমন্ত্রণ",
    "curtain.open": "আমন্ত্রণপত্র খুলুন",

    "notFound.metaTitle": "আমন্ত্রণপত্র পাওয়া যায়নি · {groom} ও {bride}",
    "notFound.kicker": "আমন্ত্রণপত্র পাওয়া যায়নি",
    "notFound.title": "এই আমন্ত্রণপত্রটি বোধহয় অন্য কোনো বিয়েবাড়িতে চলে গেছে",
    "notFound.body": "ছাদনাতলার নীচে, সানাইয়ের পিছনে, এমনকি মাসির হাতব্যাগেও খুঁজে দেখেছি, কিন্তু এই লিংকের কোনো আমন্ত্রণপত্র পেলাম না।",
    "notFound.hint": "WhatsApp-এ যে লিংকটি পেয়েছেন, ঠিক সেটিই খুলুন, অথবা পরিবারের কাছে নতুন লিংক চেয়ে নিন।",
    "notFound.ask": "WhatsApp-এ পরিবারকে জিজ্ঞাসা করুন",
    "notFound.call": "ফোন করুন: {name}",
    "sound.withSound": "শব্দ সহ",
    "sound.withoutSound": "শব্দ ছাড়া",
    "sound.mute": "সানাই বন্ধ করুন",
    "sound.unmute": "সানাই চালু করুন",
    "ambient.shankh": "শাঁখ বাজান",
    "ambient.openStory": "বিয়ের গল্প খুলুন",

    "nav.top": "উপরে ফিরে যান",
    "nav.sections": "বিভাগ",
    "nav.gallery": "ছবি",
    "nav.events": "অনুষ্ঠান",
    "nav.rituals": "আচারের পরিচয়",
    "nav.polls": "মজার ভোট",
    "nav.rsvp": "উত্তর দিন",

    "hero.dear": "প্রিয় {name},",
    "hero.blessingTitle": "শুভ পরিণয়: অনুরাগের রঙে আঁকা এক নতুন দিগন্ত",
    "hero.reply": "আমন্ত্রণের উত্তর দিন",
    "hero.seeEvents": "অনুষ্ঠানসূচি দেখুন",
    "hero.stageLabel": "{groom} ও {bride}-এর ছবি",
    "looks.label": "পোশাক বদলে দেখুন",

    "countdown.untilStart": "উৎসব শুরু হতে বাকি",
    "countdown.untilEvent": "{event} শুরু হতে বাকি",
    "countdown.begun": "উৎসব শুরু হয়ে গেছে",
    "countdown.over": "আমাদের আনন্দে শামিল হওয়ার জন্য ধন্যবাদ",
    "countdown.days": "দিন",
    "countdown.hours": "ঘণ্টা",
    "countdown.minutes": "মিনিট",
    "countdown.seconds": "সেকেন্ড",

    "families.title": "দুই পরিবার",
    "families.intro": "আনন্দে এক হচ্ছে দুটি পরিবার।",
    "families.bride": "কনে",
    "families.groom": "বর",
    "families.joiner": "ও",

    "rituals.title": "বাঙালি বিয়েতে কী কী হয়?",
    "rituals.intro": "প্রথমবার আমাদের সঙ্গে যোগ দেওয়া অতিথিদের জন্য ছোট্ট পরিচয়।",
    "rituals.pending": "নিশ্চিত হওয়া বাকি",
    "rituals.confirmed": "আমাদের আয়োজনে থাকছে",
    "rituals.pendingNotice": "পরিবার কোন কোন আচার হবে তা নিশ্চিত করছে।",
    "rituals.confirmedNotice": "{n}টি আচার নিশ্চিত হয়েছে; পারিবারিক রীতি অনুযায়ী বাকি অংশ বদলাতে পারে।",
    "rituals.objectStory": "বিয়ের একটি বস্তু",

    "dayMode.label": "বিয়ের দিনের তথ্য",
    "dayMode.kicker": "বিয়ের দিনের মোড",
    "dayMode.happening": "এখন হচ্ছে: {event}",
    "dayMode.next": "এরপর: {event} {time}-এ",
    "dayMode.lagna": "শুভ লগ্নে",
    "dayMode.timeSoon": "সময় নিশ্চিত হওয়া বাকি",
    "dayMode.celebration": "উৎসব",
    "dayMode.map": "মানচিত্র ও সূচি খুলুন",
    "dayMode.contacts": "পারিবারিক যোগাযোগ",
    "dayMode.call": "ফোন",
    "dayMode.offline": "প্রথমবার দেখার পরে এই পাতা ও দিনের জরুরি তথ্য অফলাইনেও থাকবে।",

    "gallery.title": "আমরা দুজন",
    "gallery.intro": "আমাদের একসঙ্গে কাটানো কিছু প্রিয় মুহূর্ত।",
    "gallery.openLarger": "{label}। বড় করে দেখুন",
    "gallery.emptyTitle": "আসল ছবি আসছে শিগগিরই",
    "gallery.emptyBody": "আমরা পছন্দের ছবিগুলো বাছাই করছি। ডিসেম্বরের কাছাকাছি আবার দেখুন।",

    "events.title": "কলকাতায় চারটি দিন",
    "events.intro": "সময় ও স্থান চূড়ান্ত হলেই এখানে জানিয়ে দেব।",
    "events.time": "সময়",
    "events.venue": "স্থান",
    "events.tba": "শীঘ্রই জানানো হবে",
    "events.from": "{time} থেকে",
    "events.done": "সম্পন্ন",
    "events.today": "আজ",
    "events.tomorrow": "আগামীকাল",
    "events.inDays": "আর {n} দিন",
    "events.directions": "পথনির্দেশ",
    "events.addToCalendar": "ক্যালেন্ডারে যোগ করুন",
    "events.addAria": "{event} আপনার ক্যালেন্ডারে যোগ করুন",
    "events.venueSoon": "অনুষ্ঠানস্থল চূড়ান্ত হলেই এখানে জানিয়ে দেব।",
    "events.getDirections": "পথ দেখুন",
    "events.mapOf": "{place}-এর মানচিত্র",
    "events.titleDays1": "কলকাতায় আপনার অপেক্ষায়",
    "events.titleDays2": "কলকাতায় দুটি দিন",
    "events.titleDays3": "কলকাতায় তিনটি দিন",
    "dialog.close": "বন্ধ করুন",

    "contact.open": "পরিবারের সঙ্গে যোগাযোগ",
    "contact.title": "কিছু জানার আছে? ফোন বা হোয়াটসঅ্যাপ করুন",
    "contact.groom": "বরপক্ষ",
    "contact.bride": "কনেপক্ষ",
    "contact.call": "{name}-কে {number} নম্বরে ফোন করুন",
    "contact.whatsapp": "{name}-কে {number} নম্বরে হোয়াটসঅ্যাপ করুন",

    "polls.or": "নাকি",
    "polls.intro": "প্রতিটিতে একটা পক্ষ বেছে নিন, চাইলে বাদও দিতে পারেন।",
    "polls.count": "{n}টির মধ্যে {i}",
    "polls.skip": "এটা বাদ দিন",
    "polls.next": "পরের প্রশ্ন",
    "polls.seeResults": "আপনার বাছাই দেখুন",
    "polls.votes": "{n}টি ভোট",
    "polls.oneVote": "১টি ভোট",
    "polls.early": "সবে শুরু: এখনও পর্যন্ত {n}টি ভোট",
    "polls.yourPicks": "আপনার বাছাই",
    "polls.allGroom": "আপনি পাকাপাকি #TeamGroom।",
    "polls.allBride": "আপনি পাকাপাকি #TeamBride।",
    "polls.balanced": "একদম সমান সমান। দুই পরিবারই খুশি।",
    "polls.skippedAll": "সবগুলোই বাদ দিলেন। খুবই কূটনৈতিক!",
    "polls.everyone": "এখনও পর্যন্ত সব অতিথি",
    "polls.again": "আবার খেলুন",

    "rsvp.title": "আপনি আসছেন তো?",
    "rsvp.intro": "আসতে পারুন বা না পারুন, আমাদের জানাবেন।",
    "rsvp.deadline": "{date}-এর মধ্যে জানালে ভালো হয়। আসতে পারুন বা না পারুন, আমাদের জানাবেন।",
    "rsvp.name": "আপনার নাম",
    "rsvp.phone": "হোয়াটসঅ্যাপ নম্বর",
    "rsvp.phonePlaceholder": "+৯১ ৯৮xxx xxxxx",
    "rsvp.reply": "আপনার উত্তর",
    "rsvp.yes": "অবশ্যই আসছি",
    "rsvp.no": "দুঃখিত, আসতে পারছি না",
    "rsvp.events": "কোন কোন অনুষ্ঠানে আসবেন?",
    "rsvp.guests": "আপনাকে নিয়ে মোট অতিথি",
    "rsvp.fewer": "একজন কম",
    "rsvp.more": "একজন বেশি",
    "rsvp.food": "খাবারের পছন্দ",
    "rsvp.dietNotes": "অ্যালার্জি বা অন্য কোনো প্রয়োজন",
    "rsvp.dietNotesPlaceholder": "যেমন: বাদাম চলবে না, একটি বাচ্চার খাবার",
    "rsvp.wishes": "নবদম্পতির জন্য শুভেচ্ছা",
    "rsvp.optional": "ঐচ্ছিক",
    "rsvp.send": "উত্তর পাঠান",
    "rsvp.sending": "পাঠানো হচ্ছে…",
    "rsvp.errName": "আপনার নামটা লিখুন, যাতে বুঝতে পারি কে উত্তর দিলেন।",
    "rsvp.errPhone": "যে নম্বরে আপনাকে পাওয়া যাবে সেটা লিখুন; ভারতের বাইরে হলে দেশের কোড সহ।",
    "rsvp.errAttending": "আসতে পারবেন কি না, বেছে নিন।",
    "rsvp.errEvents": "অন্তত একটি অনুষ্ঠান বেছে নিন।",
    "rsvp.errOffline": "মনে হচ্ছে আপনি এখন অফলাইন, তাই উত্তরটি এখনও পাঠানো হয়নি। আপনার উত্তরগুলো এখানেই আছে: ইন্টারনেট চালু করে আবার “উত্তর পাঠান” টিপুন।",
    "rsvp.errSlow": "পাঠাতে স্বাভাবিকের চেয়ে বেশি সময় লাগছে, তাই উত্তরটি পৌঁছেছে কি না নিশ্চিত হতে পারিনি। একটু অপেক্ষা করে আবার “উত্তর পাঠান” টিপুন।",
    "rsvp.errServer": "দুঃখিত, আমাদের দিকে একটা সমস্যা হয়েছে, উত্তরটি সেভ হয়নি। আপনার উত্তরগুলো এখানেই আছে: কয়েক মিনিট পরে আবার চেষ্টা করুন। বারবার এমন হলে হোয়াটসঅ্যাপে আমাদের জানান।",
    "rsvp.thanksYes": "ধন্যবাদ, {name}!",
    "rsvp.thanksNo": "জানানোর জন্য ধন্যবাদ, {name}।",
    "rsvp.savedOne": "আপনার জন্য জায়গা রাখা হল ({date}-এ উত্তর দিয়েছেন)। আপনার সঙ্গে আনন্দ ভাগ করে নেওয়ার অপেক্ষায় রইলাম।",
    "rsvp.savedMany": "{n}টি জায়গা রাখা হল ({date}-এ উত্তর দিয়েছেন)। আপনাদের সঙ্গে আনন্দ ভাগ করে নেওয়ার অপেক্ষায় রইলাম।",
    "rsvp.missed": "আপনাকে খুব মনে পড়বে; সেদিন আপনি আমাদের ভাবনায় থাকবেন ({date}-এ উত্তর দিয়েছেন)।",
    "rsvp.change": "উত্তর বদলান",

    "footer.blessing": "দুই পরিবারের ভালোবাসা ও আশীর্বাদ সহ।",
    "footer.petalsOff": "ঝরা পাপড়ি থামান",
    "footer.petalsOn": "ঝরা পাপড়ি চালু করুন",
    "footer.sound": "শব্দ",
    "gallery.storyCount": "{total}-এর মধ্যে {current}",
    "gallery.like": "ছবিটি পছন্দ করুন",
    "gallery.previous": "আগের ছবি",
    "gallery.next": "পরের ছবি",
    "gallery.defaultComment": "একটি ছোট্ট মুহূর্ত, পরে মনে রাখার জন্য।",
  },
};
